ecommit_deploy_rsync:
    #Environments configuration
    environments:
        my_server1: #Environment name
            hostname: ssh.cluster028.hosting.ovh.net #SSH hostname - Required
            username: danieqh #SSH username - Required
            dir: /home/danieqh #SSH remote directory - Required
            #port: 22 #Port - Not required - Default value: 22
            #rsync_options: [] #Rsync command options - Not required - Default values: [] - If not defined, the global rsync_options is used
            #ignore_file: #Rsync ignore file - Not required - Default value: null - If not defined, the global ignore_file option is used

        #You can define others environments :
        #my_server2:
            #hostname: myserver2.com
            #username: myser
            #dir: /home/remote_dir
    
    #Rsync global configuration
    #rsync:
        #rsync_path: rsync #Rsync bin path - Not required - Default value: "rsync"
        #rsync_options #Rsync command options (global) - Default values:
            # - '-azC'
            # - '--force'
            # - '--delete'
            # - '--progress'
        #ignore_file: #Rsync ignore file - Not required - Default value: null